In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
### sentences
sent=[ 'the glass of milk',
      'the glass of justice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',
      'rohitsharma is a purely a good hitter of ball',]

In [25]:
sent

['the glass of milk',
 'the glass of justice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good',
 'rohitsharma is a purely a good hitter of ball']

In [26]:
### Define the vocabulary size
voc_size=10000

In [27]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2021, 6756, 9851, 3473],
 [2021, 6756, 9851, 9742],
 [2021, 2328, 9851, 9581],
 [5842, 6875, 8505, 7624, 9903],
 [5842, 6875, 8505, 7624, 70],
 [6008, 2021, 8789, 9851, 2100],
 [8892, 3384, 7230, 7624],
 [3586, 8479, 8505, 5161, 8505, 7624, 9293, 9851, 8782]]

In [28]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [29]:
import numpy as np

In [31]:
sent_length=10
embedding_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0    0    0 2021 6756 9851 3473]
 [   0    0    0    0    0    0 2021 6756 9851 9742]
 [   0    0    0    0    0    0 2021 2328 9851 9581]
 [   0    0    0    0    0 5842 6875 8505 7624 9903]
 [   0    0    0    0    0 5842 6875 8505 7624   70]
 [   0    0    0    0    0 6008 2021 8789 9851 2100]
 [   0    0    0    0    0    0 8892 3384 7230 7624]
 [   0 3586 8479 8505 5161 8505 7624 9293 9851 8782]]


In [32]:
## feature representation
dim=10

In [33]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [38]:
model.predict(embedding_docs)

1/1 [==============================] - 0s 31ms/step


array([[[-0.01344347, -0.00968008,  0.00143487, -0.02130729,
         -0.01438015, -0.029056  ,  0.04926846, -0.00539017,
          0.01642166,  0.01557009],
        [-0.01344347, -0.00968008,  0.00143487, -0.02130729,
         -0.01438015, -0.029056  ,  0.04926846, -0.00539017,
          0.01642166,  0.01557009],
        [-0.01344347, -0.00968008,  0.00143487, -0.02130729,
         -0.01438015, -0.029056  ,  0.04926846, -0.00539017,
          0.01642166,  0.01557009],
        [-0.01344347, -0.00968008,  0.00143487, -0.02130729,
         -0.01438015, -0.029056  ,  0.04926846, -0.00539017,
          0.01642166,  0.01557009],
        [-0.01344347, -0.00968008,  0.00143487, -0.02130729,
         -0.01438015, -0.029056  ,  0.04926846, -0.00539017,
          0.01642166,  0.01557009],
        [-0.01344347, -0.00968008,  0.00143487, -0.02130729,
         -0.01438015, -0.029056  ,  0.04926846, -0.00539017,
          0.01642166,  0.01557009],
        [ 0.04216117, -0.00936586, -0.04417275,  0.0

In [40]:
embedding_docs[0]

array([   0,    0,    0,    0,    0,    0, 2021, 6756, 9851, 3473])

In [45]:
model.predict(embedding_docs[0])

1/1 [==============================] - 0s 46ms/step


array([[-0.01344347, -0.00968008,  0.00143487, -0.02130729, -0.01438015,
        -0.029056  ,  0.04926846, -0.00539017,  0.01642166,  0.01557009],
       [-0.01344347, -0.00968008,  0.00143487, -0.02130729, -0.01438015,
        -0.029056  ,  0.04926846, -0.00539017,  0.01642166,  0.01557009],
       [-0.01344347, -0.00968008,  0.00143487, -0.02130729, -0.01438015,
        -0.029056  ,  0.04926846, -0.00539017,  0.01642166,  0.01557009],
       [-0.01344347, -0.00968008,  0.00143487, -0.02130729, -0.01438015,
        -0.029056  ,  0.04926846, -0.00539017,  0.01642166,  0.01557009],
       [-0.01344347, -0.00968008,  0.00143487, -0.02130729, -0.01438015,
        -0.029056  ,  0.04926846, -0.00539017,  0.01642166,  0.01557009],
       [-0.01344347, -0.00968008,  0.00143487, -0.02130729, -0.01438015,
        -0.029056  ,  0.04926846, -0.00539017,  0.01642166,  0.01557009],
       [ 0.04216117, -0.00936586, -0.04417275,  0.03821677, -0.00815581,
        -0.04674667,  0.02412977,  0.00703581